// M2-09 - the Zone 6 (Prioritize) surface: triage, then the anti-anchoring commit.
//
// A PURE VIEW over the M2-01 store. The store is never the source of truth: the
// candidate list reads canvas.opportunities (a C9 projection), and every change
// leaves the UI as either an opportunity.created upsert (triage / rung) or a
// score.committed event (the scoring commit).
//
// Two-stage convergence (spec v0.3 A5 + v0.2 section 9):
//   Stage 1 - Triage: sort every candidate into Now / Maybe / No, fast and gut-level,
//             NO numbers. Full scoring is reachable only for the Now pile.
//   Stage 2 - Score the Now pile: set benefit + effort 1-5, pick a taxonomy rung, and
//             Commit. The anti-anchoring rule (hard rule): the agent is silent on a
//             score until Commit fires score.committed; an uncommitted Now item is a
//             "ghost" (spec's ghost dot). Committing derives the 2x2 quadrant.
//
// Ids/scores are minted/entered HERE, at the app edge; the store stays pure.
//
// Layering (constitution / AGENTS.md): committing makes no judgement about whether a
// score is right. It only shapes the score.committed candidate; the precompiled ajv
// validator in the C8 store decides acceptance and C9 merges score+committed onto the
// opportunity. No agent opinion is possible before that event exists.

import { useEffect, useMemo, useState } from 'react'
import type { StoreApi } from 'zustand/vanilla'
import type { LlmClient } from '@procezio/core'
import type { ChallengePayload, Opportunity, Score, TaxonomyRung } from '@procezio/schema'
import type { CanvasStoreState } from '../store/canvas-store.js'
import { getCanvas } from '../store/canvas-store.js'
import { useCanvasStore } from '../store/use-canvas-store.js'
import { theme } from '../theme.js'
import { meetsTier } from '../rules/nudges.js'
import { challengeCandidate } from '../tasks/challenge.js'
import { assembleEvidence } from '../tasks/challenger.js'
import {
  RUNG_HELP,
  SCORE_VALUES,
  TAXONOMY_RUNGS,
  TRIAGE_PILES,
  buildOpportunityUpsertCandidate,
  buildScoreCommittedCandidate,
  quadrantFor,
  type TriagePile,
} from './events.js'
// The pure derivations (Now pile, shortlist health, draft-score completeness/dirty,
// triage-reason change detection) live in ./model.ts so they run headless under
// node:test; this file stays presentational.
import {
  committedCountOf,
  completedScore,
  isHealthyShortlist,
  isScoreDirty,
  nowPileOf,
  triageReasonPatch,
} from './model.js'

export interface PrioritizeZoneProps {
  store: StoreApi<CanvasStoreState>
  /** The connected model (or null). At T1+, committing a score raises an evidence-cited challenge. */
  client?: LlmClient | null
}

/** Quadrant badge colour: Quick Win / Fill-in read as pass-ish, Avoid as friction. */
function quadrantColor(q: string): string {
  if (q === 'Quick Win') return theme.pass
  if (q === 'Avoid') return theme.friction
  if (q === 'Strategic') return theme.accent
  return theme.textMuted
}

export function PrioritizeZone({ store, client }: PrioritizeZoneProps): JSX.Element {
  const canvas = useCanvasStore(store, getCanvas)
  const sessionId = useCanvasStore(store, (s) => s.sessionId)
  const dispatch = useCanvasStore(store, (s) => s.dispatch)
  const tier = useCanvasStore(store, (s) => s.tier)

  const opportunities = canvas.opportunities ?? []
  const canMutate = sessionId !== null
  // The evidence-cited challenge per opportunity, generated by the agent after commit
  // (spec section 9). Held in local UI state; the challenge.raised event is the audit log.
  const [challenges, setChallenges] = useState<Record<string, ChallengePayload>>({})

  // After a commit, if a model is connected at T1+, ask it to raise the single
  // evidence-cited challenge. The rule already decided to challenge; this only words it.
  const raiseChallenge = (o: Opportunity, score: Score): void => {
    if (client === null || client === undefined || sessionId === null || !meetsTier('T1', tier))
      return
    const ctx = {
      opportunityId: o.id,
      title: o.title,
      benefit: score.benefit,
      effort: score.effort,
      evidence: assembleEvidence(canvas),
    }
    void challengeCandidate(client, sessionId, ctx).then((cand) => {
      if (cand === null) return
      dispatch(cand)
      setChallenges((c) => ({ ...c, [o.id]: cand.payload as ChallengePayload }))
    })
  }
  const dismissChallenge = (oppId: string): void =>
    setChallenges((c) => {
      const next = { ...c }
      delete next[oppId]
      return next
    })

  const nowPile = useMemo(() => nowPileOf(opportunities), [opportunities])
  const committedCount = committedCountOf(nowPile)
  const healthyShortlist = isHealthyShortlist(committedCount)

  const setTriage = (o: Opportunity, pile: TriagePile): void => {
    if (sessionId === null) return
    dispatch(buildOpportunityUpsertCandidate(sessionId, o, { triage: pile }))
  }

  // Decision journal (G3): log why an idea landed in its pile. Only writes on a real
  // change - triageReasonPatch (model.ts) returns null for an unchanged blur.
  const saveTriageReason = (o: Opportunity, reason: string): void => {
    if (sessionId === null) return
    const next = triageReasonPatch(o, reason)
    if (next === null) return
    dispatch(buildOpportunityUpsertCandidate(sessionId, o, { triage_reason: next }))
  }

  // --- Empty state: no candidates yet - point back to Ideation. -----------------
  if (opportunities.length === 0) {
    return (
      <div
        style={{
          height: '100%',
          width: '100%',
          overflowY: 'auto',
          boxSizing: 'border-box',
          padding: '16px 18px',
        }}
      >
        <div style={{ maxWidth: 700 }}>
          <ZoneHeader />
          <div
            style={{
              marginTop: 24,
              padding: '22px 24px',
              border: `1px dashed ${theme.border}`,
              borderRadius: 10,
              background: theme.surface,
              fontSize: 15,
              lineHeight: 1.55,
              color: theme.textMuted,
            }}
          >
            No candidates to prioritize yet. Generate some ideas in <strong>Ideation</strong> (Zone
            5) first - you triage and score them here.
          </div>
        </div>
      </div>
    )
  }

  return (
    <div
      style={{
        height: '100%',
        width: '100%',
        overflowY: 'auto',
        boxSizing: 'border-box',
        padding: '16px 18px',
      }}
    >
      <div style={{ maxWidth: 860 }}>
        <ZoneHeader />

        {/* Stage 1 - Triage. Fast, gut-level, no numbers. */}
        <SectionLabel
          step="1"
          title="Triage"
          hint="Sort every idea into a pile. Fast and gut-level - no numbers yet."
        />
        <ul
          style={{
            listStyle: 'none',
            margin: '0 0 40px',
            padding: 0,
            display: 'flex',
            flexDirection: 'column',
            gap: 8,
          }}
        >
          {opportunities.map((o) => (
            <li
              key={o.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 8,
                padding: '11px 14px',
                border: `1px solid ${theme.border}`,
                borderRadius: 8,
                background: theme.surface,
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                <span
                  style={{ flex: '1 1 auto', fontSize: 15, color: theme.text, lineHeight: 1.4 }}
                >
                  {o.title}
                </span>
                <div style={{ flex: '0 0 auto', display: 'flex', gap: 6 }}>
                  {TRIAGE_PILES.map((pile) => {
                    const active = o.triage === pile
                    return (
                      <button
                        key={pile}
                        type="button"
                        onClick={() => setTriage(o, pile)}
                        disabled={!canMutate}
                        aria-pressed={active}
                        style={{
                          cursor: canMutate ? 'pointer' : 'default',
                          border: `1px solid ${active ? theme.accent : theme.border}`,
                          borderRadius: 999,
                          padding: '5px 13px',
                          fontSize: 13,
                          fontWeight: active ? 700 : 500,
                          color: active ? theme.onAccent : theme.text,
                          background: active ? theme.accent : '#ffffff',
                        }}
                      >
                        {pile}
                      </button>
                    )
                  })}
                </div>
              </div>
              {/* Decision journal (G3): why this pile? Logged so a Maybe/No is defensible later. */}
              {o.triage !== undefined && (
                <input
                  type="text"
                  defaultValue={o.triage_reason ?? ''}
                  disabled={!canMutate}
                  onBlur={(e) => saveTriageReason(o, e.target.value)}
                  placeholder={`Why ${o.triage}? (optional - logged in the decision journal)`}
                  aria-label={`Reason for triaging ${o.title} as ${o.triage}`}
                  style={{
                    fontSize: 12.5,
                    padding: '5px 8px',
                    border: `1px solid ${theme.border}`,
                    borderRadius: 6,
                    color: theme.textMuted,
                    fontFamily: theme.sans,
                  }}
                />
              )}
            </li>
          ))}
        </ul>

        {/* Stage 2 - Score the Now pile (only). */}
        <SectionLabel
          step="2"
          title="Score the Now pile"
          hint="Only the Now pile is scored. Set benefit and effort, pick how you'd improve it, then Commit - the agent stays silent until you do."
        />
        {nowPile.length === 0 ? (
          <p style={{ fontSize: 14, color: theme.textMuted, margin: '0 0 8px' }}>
            Nothing in the Now pile yet. Move an idea to <strong>Now</strong> above to score it.
          </p>
        ) : (
          <>
            <div
              style={{
                fontSize: 13,
                color: healthyShortlist ? theme.pass : theme.textMuted,
                fontWeight: healthyShortlist ? 600 : 400,
                marginBottom: 14,
              }}
            >
              {committedCount} of {nowPile.length} committed
              {healthyShortlist ? ' - a healthy shortlist.' : ' (aim for at least 3).'}
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {nowPile.map((o) => (
                <ScoreCard
                  key={o.id}
                  opportunity={o}
                  disabled={!canMutate}
                  challenge={challenges[o.id]}
                  onDismissChallenge={() => dismissChallenge(o.id)}
                  onCommit={(score) => {
                    if (sessionId !== null) {
                      dispatch(buildScoreCommittedCandidate(sessionId, o.id, score))
                      raiseChallenge(o, score)
                    }
                  }}
                  onRung={(rung) => {
                    if (sessionId !== null)
                      dispatch(buildOpportunityUpsertCandidate(sessionId, o, { rung }))
                  }}
                />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}

// --- One Now-pile card: benefit/effort pickers, rung, Commit, quadrant. --------
interface ScoreCardProps {
  opportunity: Opportunity
  disabled: boolean
  onCommit: (score: Score) => void
  onRung: (rung: TaxonomyRung) => void
  /** The evidence-cited challenge the agent raised on this commit, if any. */
  challenge: ChallengePayload | undefined
  /** Keep the score (dismiss the challenge). Revise = just re-score above. */
  onDismissChallenge: () => void
}

function ScoreCard({
  opportunity,
  disabled,
  onCommit,
  onRung,
  challenge,
  onDismissChallenge,
}: ScoreCardProps): JSX.Element {
  const committed = opportunity.committed === true
  const [benefit, setBenefit] = useState<number | null>(opportunity.score?.benefit ?? null)
  const [effort, setEffort] = useState<number | null>(opportunity.score?.effort ?? null)

  // Re-seed the draft if this opportunity's committed score changes underneath us
  // (e.g. after a compensating undo lands in a later card).
  useEffect(() => {
    setBenefit(opportunity.score?.benefit ?? null)
    setEffort(opportunity.score?.effort ?? null)
  }, [opportunity.score?.benefit, opportunity.score?.effort])

  // completedScore is the commit path's only door: null while either axis is unset,
  // so an incomplete draft can never fire score.committed.
  const draftScore = completedScore(benefit, effort)
  const complete = draftScore !== null
  const dirty = isScoreDirty(opportunity, benefit, effort)
  const quadrant = committed && opportunity.score ? quadrantFor(opportunity.score) : null

  // A ghost until committed (spec's uncommitted "ghost dot").
  const ghost = !committed

  return (
    <div
      style={{
        border: `1px solid ${committed ? theme.border : theme.border2}`,
        borderRadius: 10,
        background: theme.surface,
        padding: '16px 18px',
        opacity: ghost ? 0.92 : 1,
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          gap: 12,
          marginBottom: 14,
        }}
      >
        <span style={{ fontSize: 16, fontWeight: 700, color: theme.text }}>
          {opportunity.title}
        </span>
        {committed && quadrant !== null ? (
          <span
            style={{
              flex: '0 0 auto',
              fontSize: 12,
              fontWeight: 700,
              color: theme.onAccent,
              background: quadrantColor(quadrant),
              borderRadius: 999,
              padding: '3px 11px',
            }}
          >
            {quadrant}
          </span>
        ) : (
          <span
            style={{
              flex: '0 0 auto',
              fontSize: 12,
              fontWeight: 600,
              color: theme.textFaint,
              fontStyle: 'italic',
            }}
          >
            not committed
          </span>
        )}
      </div>

      <AxisRow
        label="Benefit"
        hint="time saved, fewer errors, faster cycle"
        value={benefit}
        onPick={setBenefit}
        disabled={disabled}
      />
      <AxisRow
        label="Effort"
        hint="rule ambiguity, messy data, integration"
        value={effort}
        onPick={setEffort}
        disabled={disabled}
      />

      {/* Taxonomy rung - how you'd improve it (set immediately, separate from score). */}
      <div style={{ marginTop: 6, marginBottom: 8 }}>
        <div
          style={{
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: 1,
            textTransform: 'uppercase',
            color: theme.accent,
            marginBottom: 6,
          }}
        >
          How would you improve it?
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
          {TAXONOMY_RUNGS.map((rung) => {
            const active = opportunity.rung === rung
            return (
              <button
                key={rung}
                type="button"
                onClick={() => onRung(rung)}
                disabled={disabled}
                aria-pressed={active}
                title={RUNG_HELP[rung]}
                style={{
                  cursor: disabled ? 'default' : 'pointer',
                  border: `1px solid ${active ? theme.accent : theme.border}`,
                  borderRadius: 999,
                  padding: '5px 12px',
                  fontSize: 12,
                  fontWeight: active ? 700 : 500,
                  color: active ? theme.accent : theme.text,
                  background: active ? theme.accentSoft : '#ffffff',
                }}
              >
                {rung}
              </button>
            )
          })}
        </div>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginTop: 12 }}>
        <button
          type="button"
          onClick={() => {
            if (draftScore !== null) onCommit(draftScore)
          }}
          disabled={disabled || !complete || !dirty}
          style={{
            cursor: !complete || !dirty ? 'default' : 'pointer',
            border: `1px solid ${!complete || !dirty ? theme.border : theme.accent}`,
            borderRadius: 8,
            padding: '9px 20px',
            fontSize: 14,
            fontWeight: 700,
            color: !complete || !dirty ? theme.textMuted : theme.onAccent,
            background: !complete || !dirty ? theme.surface2 : theme.accent,
          }}
        >
          {committed ? 'Re-commit' : 'Commit'}
        </button>
        {committed && !dirty ? (
          <span style={{ fontSize: 13, color: theme.pass, fontWeight: 600 }}>
            Committed · benefit {opportunity.score?.benefit} · effort {opportunity.score?.effort}
          </span>
        ) : !complete ? (
          <span style={{ fontSize: 13, color: theme.textMuted }}>Set both axes to commit.</span>
        ) : (
          <span style={{ fontSize: 13, color: theme.textMuted }}>
            Commit to place it on the 2×2.
          </span>
        )}
      </div>

      {/* The single evidence-cited challenge the agent raised on commit (spec s.9).
          Born pencil, with keep-or-revise: Keep dismisses it, Revise = just re-score. */}
      {challenge !== undefined ? (
        <div
          style={{
            marginTop: 14,
            padding: '12px 14px',
            border: `1px solid ${theme.pencil}`,
            borderLeft: `3px solid ${theme.pencil}`,
            borderRadius: 8,
            background: theme.pencilSoft,
          }}
        >
          <div
            style={{
              fontSize: 10,
              fontWeight: 700,
              letterSpacing: 0.5,
              textTransform: 'uppercase',
              color: theme.pencil,
              marginBottom: 4,
            }}
          >
            ◆ Agent challenge · {challenge.dimension}
          </div>
          <div style={{ fontSize: 14, color: theme.text, lineHeight: 1.5 }}>
            {challenge.message}
          </div>
          {challenge.evidence_refs.length > 0 ? (
            <div
              style={{ fontSize: 11, color: theme.textMuted, marginTop: 6, fontFamily: theme.mono }}
            >
              cited: {challenge.evidence_refs.join(', ')}
            </div>
          ) : null}
          <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
            <button
              type="button"
              onClick={onDismissChallenge}
              style={{
                cursor: 'pointer',
                border: `1px solid ${theme.pass}`,
                borderRadius: 6,
                padding: '5px 14px',
                fontSize: 12,
                fontWeight: 700,
                color: theme.onAccent,
                background: theme.pass,
              }}
            >
              Keep my score
            </button>
            <span style={{ fontSize: 12, color: theme.textMuted, alignSelf: 'center' }}>
              or revise the score above and re-commit.
            </span>
          </div>
        </div>
      ) : null}
    </div>
  )
}

// --- One 1-5 axis of segmented score buttons. ---------------------------------
interface AxisRowProps {
  label: string
  hint: string
  value: number | null
  onPick: (v: number) => void
  disabled: boolean
}

function AxisRow({ label, hint, value, onPick, disabled }: AxisRowProps): JSX.Element {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 10 }}>
      <div style={{ flex: '0 0 128px' }}>
        <div style={{ fontSize: 13, fontWeight: 700, color: theme.text }}>{label}</div>
        <div style={{ fontSize: 11, color: theme.textMuted }}>{hint}</div>
      </div>
      <div style={{ display: 'flex', gap: 6 }} role="group" aria-label={`${label} score 1 to 5`}>
        {SCORE_VALUES.map((v) => {
          const active = v === value
          return (
            <button
              key={v}
              type="button"
              onClick={() => onPick(v)}
              disabled={disabled}
              aria-pressed={active}
              aria-label={`${label} ${v}`}
              style={{
                cursor: disabled ? 'default' : 'pointer',
                width: 38,
                height: 38,
                border: `1px solid ${active ? theme.accent : theme.border}`,
                borderRadius: 8,
                fontSize: 15,
                fontWeight: active ? 700 : 500,
                fontFamily: theme.mono,
                color: active ? theme.onAccent : theme.text,
                background: active ? theme.accent : '#ffffff',
              }}
            >
              {v}
            </button>
          )
        })}
      </div>
    </div>
  )
}

// --- Small labelled section divider. ------------------------------------------
function SectionLabel({
  step,
  title,
  hint,
}: {
  step: string
  title: string
  hint: string
}): JSX.Element {
  return (
    <div style={{ marginBottom: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <span
          style={{
            flex: '0 0 auto',
            width: 22,
            height: 22,
            borderRadius: 999,
            background: theme.accent,
            color: theme.onAccent,
            fontSize: 12,
            fontWeight: 700,
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          {step}
        </span>
        <h2 style={{ fontSize: 19, fontWeight: 700, margin: 0, color: theme.text }}>{title}</h2>
      </div>
      <p style={{ fontSize: 13, color: theme.textMuted, margin: '6px 0 0 32px', lineHeight: 1.5 }}>
        {hint}
      </p>
    </div>
  )
}

/** The zone's title block. */
// Compact intro line for the frame body: the frame header already names the zone, so this is
// just the one-line guidance (no redundant phase badge or oversized title).
function ZoneHeader(): JSX.Element {
  return (
    <p style={{ fontSize: 12.5, lineHeight: 1.5, margin: '0 0 14px', color: theme.textMuted }}>
      Triage the ideas into piles, then score the Now pile. You commit each score before the agent
      says a word - your judgment leads, evidence follows.
    </p>
  )
}
